train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /mnt/datasets/DIV2K/DIV2K_train_HR
      repeat: 20
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled-fast
    args:
      inp_size: 48
      scale_max: 4
      augment: true
  batch_size: 32

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /mnt/datasets/DIV2K/DIV2K_valid_HR
      first_k: 10
      repeat: 160
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled-fast
    args:
      inp_size: 48
      scale_max: 4
  batch_size: 32

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: lte-fast
  args:
    encoder_spec:
      name: swinir
      args:
        no_upsampling: true
    num_layer: 3
    hidden_dim: 256
    out_dim: 3


optimizer:
  name: adam
  args:
    lr: 2.e-4
epoch_max: 1000
multi_step_lr:
  milestones: [500, 800, 900, 950]
  gamma: 0.5

epoch_val: 1
epoch_save: 100

resume: ./save/_train_swinir-lte/epoch-last.pth