train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /mnt/datasets/DIV2K/DIV2K_train_HR
      repeat: 20
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 32
      scale_max: 4
      augment: true
      sample_q: 1024
  batch_size: 16

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /mnt/datasets/DIV2K/DIV2K_valid_HR
      first_k: 10
      repeat: 160
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 32
      scale_max: 4
      sample_q: 1024
  batch_size: 16

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: lte
  args:
    encoder_spec:
      name: mrh
      args:
		    otype: HashGrid
		    n_levels: 16
		    n_features_per_level: 2
		    log2_hashmap_size: 19
		    base_resolution: 16
		    per_level_scale: 2.0
    imnet_spec:
      name: tiny-mlp
      args:
        out_dim: 3
        otype: FullyFusedMLP
        activation: ReLU
        output_activation: None
        n_neurons: 128
        n_hidden_layers: 3
    hidden_dim: 128

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 1000
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_val: 1
epoch_save: 100

resume: ./save/_train_edsr-baseline-lte/epoch-last.pth